# NumPy

Name: Tanishq Gandhi

Question 1: Create a 4X2 integer array and Prints its attributes
Note: element must be a type of unsigned int16. And print the following Attributes: –

The shape of an array.
Array dimensions.
The Length of each element of the array in bytes.

In [3]:
import numpy as np
a = np.array([[1,2],[3,4],[5,6],[7,8]],dtype='int16')
dim = a.ndim
shape= a.shape
datatype = a.dtype
itemsize=a.itemsize
no_of_bytes=a.nbytes


In [4]:
print(dim)
print(shape)
print(datatype)
print(itemsize)

2
(4, 2)
int16
2
16


Question 2: Create a 5X2 integer array from a range between 100 to 200 such that the difference between each element is 10

In [13]:
arr = np.arange(100,200,10).reshape(5,2)
print(arr)

[[100 110]
 [120 130]
 [140 150]
 [160 170]
 [180 190]]


Question 3: Following is the provided numPy array. return array of items in the third column from all rows
import numpy
sampleArray = numpy.array([[11 ,22, 33], [44, 55, 66], [77, 88, 99]])
Expected Output:

Printing Input Array
[[11 22 33]
 [44 55 66]
 [77 88 99]]

 Printing array of items in the third column from all rows
[22 55 88]

In [10]:
sampleArray = np.array([[11,22,33],[44,55,66],[77,88,99]])
print(sampleArray)

sampleArray[:,1]


[[11 22 33]
 [44 55 66]
 [77 88 99]]


array([22, 55, 88])

Question 4: Following is the given numpy array return array of odd rows and even columns import numpy

sampleArray = numpy.array([[3 ,6, 9, 12], [15 ,18, 21, 24], [27 ,30, 33, 36], [39 ,42, 45, 48], [51 ,54, 57, 60]]) Expected Output:

Printing Input Array [[ 3 6 9 12] [15 18 21 24] [27 30 33 36] [39 42 45 48] [51 54 57 60]]

Printing array of odd rows and even columns [[ 6 12] [30 36] [54 60]]

In [19]:
sampleArray = np.array([[3 ,6, 9, 12], [15 ,18, 21, 24], 
[27 ,30, 33, 36], [39 ,42, 45, 48], [51 ,54, 57, 60]])

sampleArray[0::2,1::2]

array([[ 6, 12],
       [30, 36],
       [54, 60]])

Question 5: Add the following two NumPy arrays and Modify a result array by calculating the square of each element
import numpy

arrayOne = numpy.array([[5, 6, 9], [21 ,18, 27]])
arrayTwo = numpy.array([[15 ,33, 24], [4 ,7, 1]])
Expected Output:

addition of two arrays is 

[[20 39 33]
 [25 25 28]]

Result array after calculating the square of all elements

[[ 400 1521 1089]
 [ 625  625  784]]

In [21]:
arrayOne = np.array([[5, 6, 9], [21 ,18, 27]])
arrayTwo = np.array([[15 ,33, 24], [4 ,7, 1]])
arraysum = arrayOne + arrayTwo
sqarray = np.square(arraysum)
print(arraysum)
print(sqarray)

[[20 39 33]
 [25 25 28]]
[[ 400 1521 1089]
 [ 625  625  784]]


Question 7; Sort following NumPy array
7.1- by the second row and
7.2-by the second column
import numpy
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]])
Expected Output:

Printing Original array
[[34 43 73]
 [82 22 12]
 [53 94 66]]

Sorting Original array by secoond row
[[73 43 34]
 [12 22 82]
 [66 94 53]]

Sorting Original array by secoond column
[[82 22 12]
 [34 43 73]
 [53 94 66]]

In [26]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])
print(sampleArray)
print()
rowsort=sampleArray[sampleArray[1,:].argsort()]
print(rowsort)
print()
colsort=sampleArray[sampleArray[:,1].argsort()]
print(colsort)
print()

[[34 43 73]
 [82 22 12]
 [53 94 66]]

[[53 94 66]
 [82 22 12]
 [34 43 73]]

[[82 22 12]
 [34 43 73]
 [53 94 66]]



# Pandas

Question 6: Find the most expensive car company name
Print most expensive car’s company name and price.

Expected Output:

Python Pandas printing most costly car name

In [37]:
import pandas as pd
df = pd.read_csv("E:\\Automobile_data.csv")
df = df [['company','price']][df.price==df['price'].max()]
df

company    price
35  mercedes-benz  45400.0

Question 7: Find each company’s Higesht price car

In [39]:
import pandas as pd
df = pd.read_csv("E:\\Automobile_data.csv")
df.groupby('company')['price'].max()

company
alfa-romero      16500.0
audi             18920.0
bmw              41315.0
chevrolet         6575.0
dodge             6377.0
honda            12945.0
isuzu             6785.0
jaguar           36000.0
mazda            18344.0
mercedes-benz    45400.0
mitsubishi        8189.0
nissan           13499.0
porsche          37028.0
toyota           15750.0
volkswagen        9995.0
volvo            13415.0
Name: price, dtype: float64

Question 8: Concatenate two data frames using the following conditions
Create two data frames using the following two Dicts, Concatenate those two data frames and create a key for each data frame.

GermanCars = {'Company': ['Ford', 'Mercedes', 'BMV', 'Audi'], 'Price': [23845, 171995, 135925 , 71400]}
japaneseCars = {'Company': ['Toyota', 'Honda', 'Nissan', 'Mitsubishi '], 'Price': [29995, 23600, 61500 , 58900]}


In [44]:
GermanCars = {'Company': ['Ford', 'Mercedes', 'BMV', 'Audi'], 'Price': [23845, 171995, 135925 , 71400]}
df1 = pd.DataFrame.from_dict(GermanCars)
GermanCars

japaneseCars = {'Company': ['Toyota', 'Honda', 'Nissan', 'Mitsubishi '], 'Price': [29995, 23600, 61500 , 58900]}
df2 = pd.DataFrame.from_dict(japaneseCars)
japaneseCars

totaldf = pd.concat([df1, df2], keys=["Germany", "Japan"])
totaldf

Company   Price
Germany 0         Ford   23845
        1     Mercedes  171995
        2          BMV  135925
        3         Audi   71400
Japan   0       Toyota   29995
        1        Honda   23600
        2       Nissan   61500
        3  Mitsubishi    58900

Question 9: Sort all cars by Price column

In [47]:
df.sort_values('price')

index        company body-style  wheel-base  length engine-type  \
13     16      chevrolet  hatchback        88.4   141.1           l   
27     36          mazda  hatchback        93.1   159.1         ohc   
48     66         toyota  hatchback        95.7   158.7         ohc   
36     49     mitsubishi  hatchback        93.7   157.3         ohc   
28     37          mazda  hatchback        93.1   159.1         ohc   
..    ...            ...        ...         ...     ...         ...   
11     14            bmw      sedan       103.5   193.8         ohc   
35     47  mercedes-benz    hardtop       112.0   199.2        ohcv   
22     31          isuzu      sedan        94.5   155.9         ohc   
23     32          isuzu      sedan        94.5   155.9         ohc   
47     63        porsche  hatchback        98.4   175.7       dohcv   

   num-of-cylinders  horsepower  average-mileage    price  
13            three          48               47   5151.0  
27             four          68               30   5195.0  
48             four          62               35   5348.0  
36             four          68               37   5389.0  
28             four          68               31   6095.0  
..              ...         ...              ...      ...  
11              six         182               16  41315.0  
35            eight         184               14  45400.0  
22             four          70               38      NaN  
23             four          70               38      NaN  
47            eight         288               17      NaN  

[61 rows x 10 columns]

Question 10: Count total cars per company

In [49]:
df['company'].value_counts()

toyota           7
bmw              6
mazda            5
nissan           5
audi             4
mercedes-benz    4
mitsubishi       4
volkswagen       4
jaguar           3
alfa-romero      3
isuzu            3
porsche          3
honda            3
chevrolet        3
dodge            2
volvo            2
Name: company, dtype: int64